image:
  name: node:18

variables:
  ROOT_FOLDER: "." #Modify only if subfolders are needed; otherwise leave as '.'
  CURR_APP: "" #Will be changed to your React project name - should not need to be changed

  PROJECT_NAME: student-react-vend #Make sure this matches your project 

  OUTPUT_DIR: public/$PROJECT_NAME

  URL_APP: $CI_PAGES_URL/$PROJECT_NAME

.script-run-build: &script-run-build |
  echo "CURR APP:"$CURR_APP

  #Make sure directory for the app exists

  if [  ! -d "$CURR_APP" ]; then
    echo "CURRENT APP not set, or directory does not exist - nothing to build!"
  else
    cd $CURR_APP 
    echo "Create subfolder in gitlab public folder"
    mkdir $CI_PROJECT_DIR/public/$CURR_APP

    npm install
    npm run build
    echo "Copy build folder to gitlab public folder"
    cp -p -r build/* $CI_PROJECT_DIR/public/$CURR_APP 
    #echo "Your web page will be at" $CI_PAGES_URL"/"$CURR_APP

  fi
  echo "Return to the root directory"
  cd .. 

cache:
  paths:
  - node_modules/

before_script:
  - pwd
  - python3 --version
  - node --version
pages:
  stage: deploy
  script:
    - CI="" #Ignore warnings.  e.g. unused classes are warnings but will stop build w/o this
#    - echo "env"
#    - env

    - echo "Check current directory"
    - pwd
    - CURR_APP=$PROJECT_NAME
    - *script-run-build 
    - echo "URL for CLIENT:"$URL_APP
  artifacts:
    paths:
    - public
